---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
  - &build
    depends_on:
      - clone
    image: plugins/docker
    when:
      event:
        - pull_request
        - push

    name: build (aws-cli)
    settings: &build-settings
      dry_run: true
      password:
        from_secret: docker-hub.password
      username:
        from_secret: docker-hub.username

      dockerfile: aws-cli/Dockerfile
      repo: 72636c/aws-cli

  - <<: *build
    name: build (golang)
    settings:
      <<: *build-settings
      dockerfile: golang/Dockerfile
      repo: 72636c/golang

  - <<: *build
    name: build (mdbook)
    settings:
      <<: *build-settings
      dockerfile: mdbook/Dockerfile
      repo: 72636c/mdbook

  - &push
    depends_on:
      - clone
    image: plugins/docker
    when:
      branch:
        - master
      event:
        - push

    name: push (aws-cli)
    settings: &push-settings
      password:
        from_secret: docker-hub.password
      username:
        from_secret: docker-hub.username

      dockerfile: aws-cli/Dockerfile
      repo: 72636c/aws-cli
      tags:
        - 1
        - 1.16
        - 1.16-${DRONE_COMMIT_SHA}
        - latest

  - <<: *push
    name: push (golang)
    settings:
      <<: *push-settings
      dockerfile: golang/Dockerfile
      repo: 72636c/golang
      tags:
        - 1
        - 1.19
        - 1.19-${DRONE_COMMIT_SHA}
        - latest

  - <<: *push
    name: push (mdbook)
    settings:
      <<: *push-settings
      dockerfile: mdbook/Dockerfile
      repo: 72636c/mdbook
      tags:
        - 0.4.21
        - 0.4.21-${DRONE_COMMIT_SHA}
        - latest

---
kind: signature
hmac: 045c37de9b8e7bcd7f4e870020f0bcf9bc0c20b79502251a493026cb531e81c8

...
