---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

x-defaults:
  build: &build
    depends_on:
      - clone
    image: plugins/docker
    settings: &build-settings
      dry_run: true
      password:
        from_secret: docker-hub.password
      username:
        from_secret: docker-hub.username
    when:
      event:
        - pull_request
        - push

  push: &push
    depends_on:
      - clone
    image: plugins/docker
    settings: &push-settings
      password:
        from_secret: docker-hub.password
      username:
        from_secret: docker-hub.username
    when:
      branch:
        - master
      event:
        - push

steps:
  - <<: *build
    name: build (aws-cli)
    settings:
      <<: *build-settings
      dockerfile: aws-cli/Dockerfile
      repo: 72636c/aws-cli

  - <<: *build
    name: build (golang)
    settings:
      <<: *build-settings
      dockerfile: golang/Dockerfile
      repo: 72636c/golang

  - <<: *push
    name: push (aws-cli)
    settings:
      <<: *push-settings
      dockerfile: aws-cli/Dockerfile
      repo: 72636c/aws-cli
      tags:
        - 1
        - 1.16
        - 1.16-${DRONE_COMMIT_SHA}
        - latest

  - <<: *push
    name: push (golang)
    settings:
      <<: *push-settings
      dockerfile: golang/Dockerfile
      repo: 72636c/golang
      tags:
        - 1
        - 1.14
        - 1.14-${DRONE_COMMIT_SHA}
        - latest

---
kind: signature
hmac: 4deb48326b630dd670c561b551d8287f886d6b1e9791d0a1a24dbfeefb827f81
