---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
  - &build
    depends_on:
      - clone
    image: plugins/docker
    when:
      event:
        - pull_request
        - push

    name: build (aws-cli)
    settings: &build-settings
      dry_run: true
      password:
        from_secret: docker-hub.password
      username:
        from_secret: docker-hub.username

      dockerfile: aws-cli/Dockerfile
      repo: 72636c/aws-cli

  - <<: *build
    name: build (golang)
    settings:
      <<: *build-settings
      dockerfile: golang/Dockerfile
      repo: 72636c/golang

  - <<: *build
    name: build (mdbook)
    settings:
      <<: *build-settings
      dockerfile: mdbook/Dockerfile
      repo: 72636c/mdbook

  - &push
    depends_on:
      - clone
    image: plugins/docker
    when:
      branch:
        - master
      event:
        - push

    name: push (aws-cli)
    settings: &push-settings
      password:
        from_secret: docker-hub.password
      username:
        from_secret: docker-hub.username

      dockerfile: aws-cli/Dockerfile
      repo: 72636c/aws-cli
      tags:
        - 1
        - 1.16
        - 1.16-${DRONE_COMMIT_SHA}
        - latest

  - <<: *push
    name: push (golang)
    settings:
      <<: *push-settings
      dockerfile: golang/Dockerfile
      repo: 72636c/golang
      tags:
        - 1
        - 1.19
        - 1.19-${DRONE_COMMIT_SHA}
        - latest

  - <<: *push
    name: push (mdbook)
    settings:
      <<: *push-settings
      dockerfile: mdbook/Dockerfile
      repo: 72636c/mdbook
      tags:
        - 0.4.43
        - 0.4.43-${DRONE_COMMIT_SHA}
        - latest

---
kind: signature
hmac: 5dfaea947b2594c43fc4313011228ad7fa67bc32cd87f93a4029d4a02e1cd2aa

...
