---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

x-defaults:
  publish: &publish
    depends_on:
      - clone
    image: plugins/docker
    settings: &publish-settings
      password:
        from_secret: docker-hub.password
      username:
        from_secret: docker-hub.username
    when:
      branch:
        - master
      event:
        - push

steps:
  - <<: *publish
    name: publish (aws-cli)
    settings:
      <<: *publish-settings
      dockerfile: aws-cli/Dockerfile
      repo: 72636c/aws-cli
      tags:
        - 1
        - 1.16
        - 1.16-${DRONE_COMMIT_SHA}
        - latest

  - <<: *publish
    name: publish (golang)
    settings:
      <<: *publish-settings
      dockerfile: golang/Dockerfile
      repo: 72636c/golang
      tags:
        - 1
        - 1.12
        - 1.12-${DRONE_COMMIT_SHA}
        - latest

---
kind: signature
hmac: 189d3e8bb831e77cb0cc103f86e1cafd48ced8050aab9a40fa1ef2c8d7dee217
