name: Publish

on:
  push:
    branches:
      - $default-branch
      - mdbook-arm64

jobs:
  docker-hub:
    name: Docker Hub
    runs-on: ubuntu-24.04-arm
    permissions:
      attestations: write
      contents: read
      id-token: write
    env:
      REGISTRY: docker.io
      IMAGE_NAME: 72636c/mdbook
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5

      - name: Log in to registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@67a2d409c0a876cbe6b11854e3e25193efe4e62d
        id: push
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: mdbook/Dockerfile
          push: true
          tags: |
            0.4.43
            0.4.43-${GITHUB_SHA}
            latest

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
