name: Publish

on: push

jobs:
  docker-hub:
    name: Docker Hub
    runs-on: ubuntu-24.04-arm
    permissions:
      attestations: write
      contents: read
      id-token: write
    env:
      REGISTRY: docker.io
      USER: 72636c
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5

      - name: Log in to registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push image (golang)
        uses: docker/build-push-action@67a2d409c0a876cbe6b11854e3e25193efe4e62d
        id: golang
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: golang/Dockerfile
          push: ${{ github.ref_name == github.event.repository.default_branch }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.USER }}/golang:1.23
            ${{ env.REGISTRY }}/${{ env.USER }}/golang:1.23-${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.USER }}/golang:latest

      - name: Build & push image (mdbook)
        uses: docker/build-push-action@67a2d409c0a876cbe6b11854e3e25193efe4e62d
        id: mdbook
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: mdbook/Dockerfile
          push: ${{ github.ref_name == github.event.repository.default_branch }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.USER }}/mdbook:0.4.43
            ${{ env.REGISTRY }}/${{ env.USER }}/mdbook:0.4.43-${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.USER }}/mdbook:latest

      - name: Generate attestation (golang)
        if: github.ref_name == github.event.repository.default_branch
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.USER }}/golang
          subject-digest: ${{ steps.golang.outputs.digest }}
          push-to-registry: true

      - name: Generate attestation (mdbook)
        if: github.ref_name == github.event.repository.default_branch
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.USER }}/mdbook
          subject-digest: ${{ steps.mdbook.outputs.digest }}
          push-to-registry: true
